# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc4bf1a3b9092be480825a48867bcbee85877427e074c58e6987fe1af3e65a6cafdcbdfb07985bf5d5a5b4836df46434fb6cf86039d5e46baa06e7c4acf7b66b

test:
  secret_key_base: b96c0cef16870a11bc37a6455ed4e29af07cac615eec67436ca7ef521905db07ac5edeb24e233870560dfbbf872e9d9e757408835101c2d5d3d722a3aab38c69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
